---

- name: Download dotnet installer
  get_url:
    url: https://dot.net/v1/dotnet-install.sh
    dest: /tmp/dotnet-install.sh
    mode: "1777"

- name: Install latest version of dotnet
  script: /tmp/dotnet-install.sh
  when: dotnet_version is undefined
  
- name: Install latest version of dotnet
  script: /tmp/dotnet-install.sh --version {{ dotnet_version }}
  when: dotnet_version is defined