---

- name: Install nvm
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/${NVM_VERSION}/install.sh
    dest: /tmp/node-install.sh
    mode: "0755"

- name: Execute pyenv script
  shell: /tmp/node-install.sh
  ignore_errors: true

- name: Install the latest version of node
  shell: nvm install node
  register: latest_version
  when: node_version is undefined

- name: Install specified python version
  shell: nvm install {{ node_version }}
  when: node_version is defined