---
# https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-yum?view=azure-cli-latest

- name: install Microsoft rpm key
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: create local azure-cli repository information
  yum_repository:
    name: azure-cli
    description: Azure CLI
    baseurl: https://packages.microsoft.com/yumrepos/azure-cli
    enabled: 1
    gpgcheck: 1
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: install azure-cli
  yum:
    name: azure-cli
    state: present
