---
# Install various cloud CLIs and tools

- name: assert supported distributions and versions
  assert:
    that:
      - ( ansible_distribution == "RedHat" and ( ansible_distribution_major_version == '8' )
        ) or
        ( ansible_distribution == "CentOS" and ( ansible_distribution_major_version == "7" )
        ) or
        ( ansible_distribution == "Fedora" and ( ansible_distribution_major_version == "30" )
        )

- include: docker-compose.yml
  when: install_compose

- include: kompose.yml
  when: install_kompose

- include: kubectl.yml
  when: install_kubectl

- include: helm.yml
  when: install_helm

- include: aws.yml
  when: install_aws

- include: azure.yml
  when: install_azure

- include: ibmcloud.yml
  when: install_ibmcloud

- include: oc.yml
  when: install_oc
